############################################
# VPC ENDPOINT OUTPUTS
############################################

# ---------- S3 Gateway Endpoint ----------

output "s3_gateway_endpoint_id" {
  description = "The ID of the S3 Gateway VPC endpoint."
  value       = aws_vpc_endpoint.s3.id
}

output "s3_gateway_endpoint_arn" {
  description = "The ARN of the S3 Gateway VPC endpoint."
  value       = aws_vpc_endpoint.s3.arn
}

# ---------- SSM Interface Endpoints ----------

output "ssm_interface_endpoint_ids" {
  description = "Map of SSM-related interface VPC endpoint IDs keyed by service name."
  value       = { for k, v in aws_vpc_endpoint.ssm_interfaces : k => v.id }
}

output "ssm_interface_endpoint_network_interface_ids" {
  description = "Map of network interface IDs attached to the SSM VPC endpoints."
  value       = { for k, v in aws_vpc_endpoint.ssm_interfaces : k => v.network_interface_ids }
}

output "ssm_interface_endpoint_dns_entries" {
  description = "Map of DNS entries for the SSM interface VPC endpoints."
  value       = { for k, v in aws_vpc_endpoint.ssm_interfaces : k => v.dns_entry }
}

# ---------- Secrets Manager Interface Endpoint ----------

output "secretsmanager_endpoint_id" {
  description = "The ID of the Secrets Manager Interface VPC endpoint."
  value       = aws_vpc_endpoint.secretsmanager.id
}

output "secretsmanager_endpoint_arn" {
  description = "The ARN of the Secrets Manager Interface VPC endpoint."
  value       = aws_vpc_endpoint.secretsmanager.arn
}

output "secretsmanager_endpoint_network_interface_ids" {
  description = "List of network interface IDs attached to the Secrets Manager VPC endpoint."
  value       = aws_vpc_endpoint.secretsmanager.network_interface_ids
}

output "secretsmanager_endpoint_dns_entry" {
  description = "The DNS entries generated by the Secrets Manager VPC endpoint."
  value       = aws_vpc_endpoint.secretsmanager.dns_entry
}
